### PR TITLE
Fix interpolated string rendering issues

### LINKED ISSUE #458: Multiline interpolated strings produces invalid backslashes
Easy reproduction
https://roblox-ts.com/playground/#code/O4QwTgdgFABgNgewQawAQElUgLYFgBQIq2ArnAC4CWclEApqgM7li0DmMAlEA

```ts
warn(`look I am
a multiline string`)
```

produces
```lua
warn(`look I am
\
a multiline string`)
```

The actual emit should be
```lua
warn(`look I am\
a multiline string`)
```

### PR DESCRIPTION
**Pull request by osyrisrblx**
Fixes #458 and #484

## #458: Incorrect escaping for multi-line interpolated string literals

The issue was that the escape logic did not pick up Windows-style line endings properly. For this we need to also check for `\r` followed by an optional `\n`.

### Input
```ts
warn(`look I am
a multiline string`)
```

### Before
```luau
warn(`look I am
\
a multiline string`)
```

### After
```luau
warn(`look I am\
a multiline string`)
```

### Input
```ts
const string_a = "\u{E000}";
const string_b = `\u{E000}`;
```

### Before
```luau
local string_a = "\u{E000}"
local string_b = `\u\{E000\}`
```

### After
```luau
local string_a = "\u{E000}"
local string_b = `\u{E000}`
```

### CODE REVIEW

File: src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts [hunk 1]
```diff
@@ -2,8 +2,11 @@ import luau from "LuauAST";
...
 
 export function renderInterpolatedStringPart(state: RenderState, node: luau.InterpolatedStringPart) {
-	// braces and newlines are escaped to be valid in luau
-	// () captures result, [] to search for any of: {}
-	// $1 fills in capture from original search
-	return node.text.replace(/([{}])/g, "\\$1").replace(/\n/g, "\\\n");
+	// escape braces and newlines, but do not touch braces within unicode escape codes
+	return node.text
+		.replace(
+			/(\\u\{[0-9A-Fa-f]+\})|([{}])/g,
```
Comment (Dionysusnu) [inline src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts:8]: This regex would be cleaner with a negative lookbehind instead of capturing the Unicode sequences to like-for-like replace them. Was it a conscious decision not to use one?

File: src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts [hunk 2]
```diff
@@ -2,8 +2,11 @@ import luau from "LuauAST";
...
+			(_, unicodeEscape: string | undefined, brace: string | undefined) => unicodeEscape ?? "\\" + brace,
+		)
+		.replace(/(\r\n?|\n)/g, "\\$1");
```
Comment (Dionysusnu) [inline src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts:11]:
```suggestion
		// Captures a CR with optionally an LF after it
		// Or just an LF on its own
		.replace(/(\r\n?|\n)/g, "\\$1");
```

File: src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts (hunk 1 above)
Comment (osyrisrblx) [reply src/LuauRenderer/nodes/fields/renderInterpolatedStringPart.ts:8]: I wasn't able to find a way to do this that was readable. Open to suggestions.

**Review by Dionysusnu — APPROVED** [review]
